CREATE TABLE [Cisco].[SkillGroupInterval](
	[SkillGroupIntervalID] [bigint] IDENTITY(1,1) NOT NULL,
	[Date] [date] NULL,
	[Time] [time](7) NULL,
	[PrecisionQueueKey] [bigint] NULL,
	[SkillGroupKey] [bigint] NULL,
	[SourceSystemKey] [int] NULL,
	[TimeZone] [int] NULL,
	[CallbackMessages] [int] NULL,
	[CallbackMessagesTime] [int] NULL,
	[AvgHandledCallsTalkTime] [int] NULL,
	[HoldTime] [int] NULL,
	[HandledCallsTalkTime] [int] NULL,
	[InternalCalls] [int] NULL,
	[InternalCallsTime] [int] NULL,
	[CallsHandled] [int] NULL,
	[AvgHandledCallsTime] [int] NULL,
	[HandledCallsTime] [int] NULL,
	[PercentUtilization] [real] NULL,
	[AgentOutCallsTime] [int] NULL,
	[TalkInTime] [int] NULL,
	[LoggedOnTime] [int] NULL,
	[AgentOutCalls] [int] NULL,
	[TalkOutTime] [int] NULL,
	[TalkOtherTime] [int] NULL,
	[AvailTime] [int] NULL,
	[NotReadyTime] [int] NULL,
	[TransferInCalls] [int] NULL,
	[TalkTime] [int] NULL,
	[TransferInCallsTime] [int] NULL,
	[WorkReadyTime] [int] NULL,
	[TransferOutCalls] [int] NULL,
	[WorkNotReadyTime] [int] NULL,
	[BusyOtherTime] [int] NULL,
	[CallsAnswered] [int] NULL,
	[ReservedStateTime] [int] NULL,
	[AnswerWaitTime] [int] NULL,
	[AbandonRingCalls] [int] NULL,
	[AbandonRingTime] [int] NULL,
	[AbandonHoldCalls] [int] NULL,
	[AgentOutCallsTalkTime] [int] NULL,
	[AgentOutCallsOnHold] [int] NULL,
	[AgentOutCallsOnHoldTime] [int] NULL,
	[ConsultativeCalls] [int] NULL,
	[ConsultativeCallsTime] [int] NULL,
	[ConferencedInCalls] [int] NULL,
	[ConferencedInCallsTime] [int] NULL,
	[ConferencedOutCalls] [int] NULL,
	[ConferencedOutCallsTime] [int] NULL,
	[IncomingCallsOnHoldTime] [int] NULL,
	[IncomingCallsOnHold] [int] NULL,
	[InternalCallsOnHoldTime] [int] NULL,
	[InternalCallsOnHold] [int] NULL,
	[InternalCallsRcvdTime] [int] NULL,
	[InternalCallsRcvd] [int] NULL,
	[RedirectNoAnsCalls] [int] NULL,
	[RedirectNoAnsCallsTime] [int] NULL,
	[ShortCalls] [int] NULL,
	[BargeInCalls] [int] NULL,
	[MonitorCalls] [int] NULL,
	[CallsOffered] [int] NULL,
	[InterruptedTime] [int] NULL,
	[AbandonHoldCallsOut] [int] NULL,
	[RouterCallsOffered] [int] NULL,
	[RouterCallsAbandToAgent] [int] NULL,
	[ServiceLevel] [real] NULL,
	[ReportingHalfHour] [int] NULL,
	[ReportingInterval] [int] NULL,
	[RouterMaxCallWaitTime] [int] NULL,
	[RunID] [int] NULL,
	[EffectiveFrom] [datetime] NULL,
	[EffectiveTo] [datetime] NULL,
	[CheckSum] [int] NULL,
 CONSTRAINT [PKSkillGroupIntervalID] PRIMARY KEY NONCLUSTERED 
(
	[SkillGroupIntervalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Cisco].[SkillGroupInterval] ADD  CONSTRAINT [dfEffectiveTo]  DEFAULT ('2999-12-31') FOR [EffectiveTo]
GO
CREATE CLUSTERED INDEX [CX_SkillGroupInterval] ON [Cisco].[SkillGroupInterval]
(
	[Date] ASC,
	[Time] ASC,
	[PrecisionQueueKey] ASC,
	[SkillGroupKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]