CREATE TABLE [Cisco].[WrapUpData](
	[WrapUpDataID] [int] IDENTITY(1,1) NOT NULL,
	[WrapUpData] [varchar](60) NULL,
	[SourceSystemKey] [int] NULL,
	[RunID] [int] NULL,
	[EffectiveFrom] [datetime] NULL,
	[CheckSum] [int] NULL,
	[EffectiveTo] [datetime] NULL,
 CONSTRAINT [PKWrapUpDataID] PRIMARY KEY CLUSTERED 
(
	[WrapUpDataID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Cisco].[WrapUpData] ADD  CONSTRAINT [dfWrapUpDataEffectiveTo]  DEFAULT ('2999-12-31') FOR [EffectiveTo]
GO
CREATE NONCLUSTERED INDEX [IX_WrapUpData_WrapUpData] ON [Cisco].[WrapUpData]
(
	[WrapUpData] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]