CREATE TABLE [DataAnalysis].[DailyStepCount](
	[DailyStepCountId] [int] IDENTITY(1,1) NOT NULL,
	[OrgName] [varchar](266) NULL,
	[StepDate] [date] NOT NULL,
	[StepKey] [int] NOT NULL,
	[StepCount] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DailyStepCountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_DailyStepCount_StepDate] ON [DataAnalysis].[DailyStepCount]
(
	[StepKey] ASC,
	[StepDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]