CREATE TABLE [Bridge].[Annotation](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Violation] [varchar](150) NOT NULL,
	[Level] [varchar](12) NOT NULL,
	[TestSessionKey] [bigint] NOT NULL,
	[ProctorKey] [int] NOT NULL,
	[Source] [varchar](50) NOT NULL,
	[Mode] [varchar](6) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Annotation_Proctor] ON [Bridge].[Annotation]
(
	[ProctorKey] ASC
)
INCLUDE([TestSessionKey]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Annotation_TestSession] ON [Bridge].[Annotation]
(
	[TestSessionKey] ASC
)
INCLUDE([ProctorKey]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]