CREATE TABLE [Bridge].[MajorIncidents](
	[MajorIncidentId] [int] IDENTITY(1,1) NOT NULL,
	[TestSessionKey] [bigint] NOT NULL,
	[ProctorKey] [int] NOT NULL,
	[MajorIncidentReasonKey] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MajorIncidentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MajorIncidents_TestSessionKey] ON [Bridge].[MajorIncidents]
(
	[TestSessionKey] ASC
)
INCLUDE([ProctorKey]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]