CREATE TABLE [NICE].[Contacts]
(
	[ContactId] INT NOT NULL PRIMARY KEY, 
    [PointofContactKey] BigINT NOT NULL, 
    [CampaignKey]   BigInt Not null,
    [ContactKey]    Bigint Not Null,
    [SkillKey]      int not null,
    [TeamKey]       int not null,
    [TransferIndicatorKey] smallint not null,
    [Abandoned] BIT NULL, 
    [AbandonedSeconds] INT NULL, 
    [ACWSeconds] DECIMAL(10, 3) NULL, 
    [AgentSeconds] DECIMAL NULL, 
    [ContactStartDate] DATETIME NOT NULL, 
    [ACWWarehouseDate] DATETIME NOT NULL, 
    [WarehouseContactDate] DATETIME NOT NULL, 
    [DispositionNotes] VARBINARY(400) NULL, 
    [HighProficiency] BIT NOT NULL, 
    [HoldCount] INT NOT NULL, 
    [InQueSeconds] DECIMAL(10, 3) NOT NULL, 
    [IsOutBound] BIT NOT NULL, 
    [IsRefused] BIT NOT NULL, 
    [IsShortAbandon] BIT NOT NULL, 
    [IsTakeover] BIT NOT NULL, 
    [LowProficiency] SMALLINT NOT NULL, 
    [MediaSubtype] VARCHAR(10) NULL, 
    [MediaType] VARCHAR(10) NULL, 
    [PostQueSeconds] DECIMAL(10, 3) NULL, 
    [PreQueSeconds] DECIMAL(10, 3) NULL, 
    [PrimaryDispositionKey] INT NULL,
    [RefuseReasonKey]       Smallint, 
    [RefuseDate] DATETIME NULL, 
    [ReleaseSeconds] NCHAR(10) NULL, 
    [RoutingAttribute] BIT NOT NULL, 
    [RoutingTime] INT NOT NULL, 
    [ServiceLevelFlag] BIT NULL, 
    [TotalDuration] DECIMAL(10, 3) NOT NULL,
)
