CREATE TABLE [Reporting].[CiscoAgentStats] (
    [CiscoAgentStatsID]             BIGINT   IDENTITY (1, 1) NOT NULL,
    [Date]                          DATE     NULL,
    [TimeZone]                      INT      NULL,
    [AgentsKey]                     INT      NULL,
    [AgentLoggedOnTime]             INT      NULL,
    [CallsHandled]                  INT      NULL,
    [RedirectCalls]                 INT      NULL,
    [InCallsOnHold]                 INT      NULL,
    [TransferInCalls]               INT      NULL,
    [TransferOutCalls]              INT      NULL,
    [HoldTime]                      INT      NULL,
    [HandledCallsTime]              INT      NULL,
    [OnHoldTime]                    INT      NULL,
    [NotReadyTime]                  INT      NULL,
    [WrapTime]                      INT      NULL,
    [OutExtnCalls]                  INT      NULL,
    [TalkTime]                      INT      NULL,
    [AvailTime]                     INT      NULL,
    [AgentOutCallsTime]             INT      NULL,
    [AgentOutCallsTalkTime]         INT      NULL,
    [AgentTerminatedCalls]          INT      NULL,
    [TotalNotReady]                 INT      NULL,
    [TotalApprovedNRTime]           INT      NULL,
    [TotalNotApprovedNRTime]        INT      NULL,
    [Login/NoCode]                  INT      NULL,
    [Lunch]                         INT      NULL,
    [Break]                         INT      NULL,
    [Meeting/Training]              INT      NULL,
    [Personal]                      INT      NULL,
    [FollowUpWork]                  INT      NULL,
    [Email]                         INT      NULL,
    [POCTask]                       INT      NULL,
    [Chat]                          INT      NULL,
    [OutboundCalls]                 INT      NULL,
    [ExamAccomodations]             INT      NULL,
    [ManagementApproval]            INT      NULL,
    [AssignTasks-Other]             INT      NULL,
    [DisplacedCD]                   INT      NULL,
    [ACW]                           INT      NULL,
    [SocialMedia]                   INT      NULL,
    [ClosedFinesseW/OLogoutorError] INT      NULL,
    [DidNotAnswerCall]              INT      NULL,
    [Zendesk]                       INT      NULL,
    [Voicemail]                     INT      NULL,
    [TimeInOtherRCs]                INT      NULL,
    [Tech]                          INT      NULL,
    [Coaching]                      INT      NULL,
    [RunID]                         INT      NULL,
    [RunDate]                       DATETIME NULL,
    [CheckSum]                      INT      NULL,
    CONSTRAINT [PKCiscoAgentStatsID] PRIMARY KEY NONCLUSTERED ([CiscoAgentStatsID] ASC)
);


GO
CREATE CLUSTERED INDEX [CX_CiscoAgentStats]
    ON [Reporting].[CiscoAgentStats]([Date] ASC, [AgentsKey] ASC);

