CREATE TABLE [dbo].[DimCandidateIDType](
	[CandidateTypeId] [int] IDENTITY(1,1) NOT NULL,
	[CandidateIDType] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CandidateTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]