CREATE TABLE [dbo].[DimStates](
	[DimStateID] [smallint] IDENTITY(1,1) NOT NULL,
	[CountryId] [int] NOT NULL,
	[StateAbbreviation] [varchar](2) NOT NULL,
	[StateName] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DimStateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]