CREATE TABLE [dbo].[ExamHistory](
	[ExamHistoryId] [int] NOT NULL,
	[DossierKey] [nchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ExamHistoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]