CREATE TABLE [dbo].[SourceSystems](
	[SourceSystemId] [int] IDENTITY(1,1) NOT NULL,
	[SourceSystemName] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SourceSystemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]