CREATE TABLE [QATesting].[AspenClientCodes](
	[AspenClientID] [int] IDENTITY(1,1) NOT NULL,
	[ClientCode] [varchar](20) NOT NULL,
 CONSTRAINT [PK_AspenClientCodes] PRIMARY KEY CLUSTERED 
(
	[AspenClientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]