CREATE TABLE [Staging].[MultiCompletionStates](
	[MCSId] [int] IDENTITY(1,1) NOT NULL,
	[TestSessionKey] [int] NOT NULL,
	[DurationDefID] [int] NOT NULL,
	[CompletionState] [varchar](10) NOT NULL,
	[Duration] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[MCSId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MultiCompletionStates_TestSession] ON [Staging].[MultiCompletionStates]
(
	[TestSessionKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]