CREATE VIEW [Dimensions].[FormPoolSpecs_vw]
	AS 
	SELECT 
       [FormPoolSpecDBId]
      ,[BankKey]
      ,[Topic]
      ,[PoolDescription]
      ,[DateAdded]
      ,[IsDeleted]
      ,[LastUpdated]
      ,[IsValid]
      ,[LastValidated]
      ,[IsPublished]
      ,[BelowMeanTolerance]
      ,[TargetMean]
      ,[AboveMeanTolerance]
      ,[BelowSDTolerance]
      ,[BelowReliabilityTolerance]
      ,[TargetReliability]
      ,[AboveReliabilityTolerance]
      ,[BelowCutScoreTolerance]
      ,[TargetCutScore]
      ,[AboveCutScoreTolerance]
      ,[RawCut]
      ,[SurvivingFormsMinimum]
      ,[UseItemResponseTheory]
      ,[BelowCSEMTolerance]
      ,[TargetCSEMTolerance]
      ,[AboveCSEMTolerance]
      ,[IsAta]
      ,[NumberOfDesiredForms]
      ,[ScaleCut]
  FROM [$(PSI_DW)].[Dimensions].[FormPoolSpecs]
  Where [Currentflag] = 0
