CREATE VIEW [Dimensions].[Questions_vw]
	AS SELECT 
		QuestionDBID,
		SourceQuestionID,
		QuestionTitle,
		QuestionDescription,
		ContentAreaKey,
		ContentSubAreaKey,
		QuestionType,
		QuestionStatus,
		VersionNum,
		QuestionChoices,
		QuestionColumns,
		CorrectChoice,
		MaxResponses,
		PartialCredit,
		UseHints,
		ChoiceFeedback,
		MaxPoints,
		MinPoints,
		TimeLimit,
		LeadInkey,
		Admins,
		QuestionELT,
		QuestionsDiff,
		QuestionsRPB,
		QuestionsAvg,
		Omits,
		Stem,
		QuestionNotes,
		RefCollapsed,
		Feedback,
		Range1,
		Range2,
		Seed,
		Scrambled,
		MatchCase,
		ExtraPointstype,
		ExtraPoints,
		SimStart,
		QuestionState,
		QuestionClass,
		QuestionLocked,
		ContentAreaKey BankCategoryGroupKey,
		ContentSubAreaKey BankCategoryKey,
		MainQuestionKey,
		MainIdx,
		MainType,
		UserValue1,
		UserValue2,
		Uservalue3,
		Uservalue4,
		Refx,
		RefH,
		SourceID,
		Theta,
		InfTheta

	From
		[$(PSI_DW)].Dimensions.Questions (nolock)
	where
		CurrentFlag = 0