CREATE VIEW [Dimensions].[StudentTestAttributes_vw]
	AS SELECT 
		StudAttribDBID,
		StudentKey,
		TestCenterKey,
		TestScheduleKey,
		ExternalExamKey,
		SchoolCode,
		ClientCode,
		ExamCode,
		ExamPortionCode,
		BookingCode,
		GraduationDate,
		ApplicationType,
		SchoolName,
		AdminGroup,
		TimeSched,
		DateSched,
		ExternalApplicantKey,
		AspenApplicantKey,
		ExamDescription,
		AspenSchedID,
		DeliveryMethod,
		ExternalTestCenterKey,
		FormKey,
		ExternalSchoolKey,
		Client,
		ADAMultiplier,
		ADAEnable,
		OrigExamPortionID,
		NationStateCd,
		ComboEnable,
		HistoryEnable,
		Licsense License,
		Degree,
		NationStatePFA,
		DeploymentEnable,
		EndEligiblityDate,
		ResponsibleEmp,
		SeatCode
	from
		[$(PSI_DW)].Dimensions.StudentTestAttributes (nolock)
	where
		CurrentFlag = 0
