CREATE TABLE [TzDb].[Links](
	[LinkZoneId] [int] NOT NULL,
	[CanonicalZoneId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LinkZoneId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [TzDb].[Links]  WITH CHECK ADD  CONSTRAINT [FK_Links_Zones] FOREIGN KEY([LinkZoneId])
REFERENCES [TzDb].[Zones] ([Id])
GO

ALTER TABLE [TzDb].[Links] CHECK CONSTRAINT [FK_Links_Zones]
GO
ALTER TABLE [TzDb].[Links]  WITH CHECK ADD  CONSTRAINT [FK_Links_Zones2] FOREIGN KEY([CanonicalZoneId])
REFERENCES [TzDb].[Zones] ([Id])
GO

ALTER TABLE [TzDb].[Links] CHECK CONSTRAINT [FK_Links_Zones2]