CREATE TABLE [Cisco].[AgentSkillGroupInterval] (
    [AgentSkillGroupIntervalId] BIGINT   IDENTITY (1, 1) NOT NULL,
    [Date]                      DATE     NULL,
    [Time]                      TIME (7) NULL,
    [AgentsKey]                 INT      NULL,
    [PrecisionQueueKey]         INT      NULL,
    [SkillGroupSkillTargetID]   INT      NULL,
    [SourceSystemKey]           INT      NULL,
    [TimeZone]                  INT      NULL,
    [AbandonRingCalls]          INT      NULL,
    [AbandonRingTime]           INT      NULL,
    [AbandonHoldCalls]          INT      NULL,
    [AgentOutCallsTime]         INT      NULL,
    [AgentOutCallsTalkTime]     INT      NULL,
    [AgentOutCalls]             INT      NULL,
    [AgentOutCallsOnHold]       INT      NULL,
    [AgentOutCallsOnHoldTime]   INT      NULL,
    [AgentTerminatedCalls]      INT      NULL,
    [AnswerWaitTime]            INT      NULL,
    [AvailTime]                 INT      NULL,
    [BusyOtherTime]             INT      NULL,
    [CallbackMessagesTime]      INT      NULL,
    [CallbackMessages]          INT      NULL,
    [CallsAnswered]             INT      NULL,
    [CallsHandled]              INT      NULL,
    [ConsultativeCalls]         INT      NULL,
    [ConsultativeCallsTime]     INT      NULL,
    [ConferencedInCalls]        INT      NULL,
    [ConferencedInCallsTime]    INT      NULL,
    [ConferencedOutCalls]       INT      NULL,
    [ConferencedOutCallsTime]   INT      NULL,
    [HandledCallsTalkTime]      INT      NULL,
    [HandledCallsTime]          INT      NULL,
    [HoldTime]                  INT      NULL,
    [IncomingCallsOnHoldTime]   INT      NULL,
    [IncomingCallsOnHold]       INT      NULL,
    [InternalCallsOnHoldTime]   INT      NULL,
    [InternalCallsOnHold]       INT      NULL,
    [InternalCallsRcvdTime]     INT      NULL,
    [InternalCallsRcvd]         INT      NULL,
    [InternalCallsTime]         INT      NULL,
    [InternalCalls]             INT      NULL,
    [LoggedOnTime]              INT      NULL,
    [NotReadyTime]              INT      NULL,
    [RedirectNoAnsCalls]        INT      NULL,
    [RedirectNoAnsCallsTime]    INT      NULL,
    [ReservedStateTime]         INT      NULL,
    [ShortCalls]                INT      NULL,
    [TalkInTime]                INT      NULL,
    [TalkOtherTime]             INT      NULL,
    [TalkOutTime]               INT      NULL,
    [TransferredInCallsTime]    INT      NULL,
    [TransferredInCalls]        INT      NULL,
    [TransferredOutCalls]       INT      NULL,
    [WorkNotReadyTime]          INT      NULL,
    [WorkReadyTime]             INT      NULL,
    [PreviewCallsOnHold]        INT      NULL,
    [BargeInCalls]              INT      NULL,
    [MonitorCalls]              INT      NULL,
    [InterruptedTime]           INT      NULL,
    [AbandonHoldOutCalls]       INT      NULL,
    [ReportingHalfHour]         INT      NULL,
    [ReportingInterval]         INT      NULL,
    [AttributeID1]              INT      NULL,
    [AttributeID2]              INT      NULL,
    [RunID]                     INT      NULL,
    [EffectiveFrom]             DATETIME NULL,
    [CheckSum]                  INT      NULL,
    [EffectiveTo]               DATETIME CONSTRAINT [dfAgentSkillGroupIntervalEffectiveTo] DEFAULT ('2999-12-31') NULL,
    CONSTRAINT [PKAgentSkillGroupIntervalId] PRIMARY KEY NONCLUSTERED ([AgentSkillGroupIntervalId] ASC)
);


GO
CREATE CLUSTERED INDEX [CX_AgentSkillGroupInterval]
    ON [Cisco].[AgentSkillGroupInterval]([Date] ASC, [Time] ASC, [AgentsKey] ASC, [PrecisionQueueKey] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_AgentSkillGroupInterval_Column_1]
    ON [Cisco].[AgentSkillGroupInterval]([SkillGroupSkillTargetID] ASC);

