CREATE TABLE [Cisco].[CallTypeInterval] (
    [CallTypeIntervalID]       BIGINT   IDENTITY (1, 1) NOT NULL,
    [Date]                     DATE     NULL,
    [Time]                     TIME (7) NULL,
    [CallTypeKey]              INT      NULL,
    [SourceSystemKey]          INT      NULL,
    [TimeZone]                 INT      NULL,
    [RouterQueueWaitTime]      INT      NULL,
    [RouterQueueCalls]         INT      NULL,
    [AvgRouterDelayQ]          INT      NULL,
    [RouterCallsAbandQ]        INT      NULL,
    [RouterQueueCallTypeLimit] INT      NULL,
    [CallsRouted]              INT      NULL,
    [ErrorCount]               INT      NULL,
    [ReturnRing]               INT      NULL,
    [AnswerWaitTime]           INT      NULL,
    [CallsHandled]             INT      NULL,
    [CallsOffered]             INT      NULL,
    [HandleTime]               INT      NULL,
    [ServiceLevelAband]        INT      NULL,
    [ServiceLevelCalls]        INT      NULL,
    [ServiceLevelCallsOffered] INT      NULL,
    [ServiceLevel]             REAL     NULL,
    [TalkTime]                 INT      NULL,
    [OverflowOut]              INT      NULL,
    [HoldTime]                 INT      NULL,
    [IncompleteCalls]          INT      NULL,
    [ShortCalls]               INT      NULL,
    [DelayQAbandTime]          INT      NULL,
    [CallsAnswered]            INT      NULL,
    [CallsRoutedNonAgent]      INT      NULL,
    [CallsRONA]                INT      NULL,
    [ReturnRelease]            INT      NULL,
    [CallsQHandled]            INT      NULL,
    [VruForcedXferredCalls]    INT      NULL,
    [ServiceLevelType]         INT      NULL,
    [BucketIntervalID]         INT      NULL,
    [CallsRequeried]           INT      NULL,
    [RouterCallsAbandToAgent]  INT      NULL,
    [TotalCallsAband]          INT      NULL,
    [DelayAgentAbandTime]      INT      NULL,
    [CallDelayAbandTime]       INT      NULL,
    [CTDelayAbandTime]         INT      NULL,
    [ServiceLevelError]        INT      NULL,
    [ServiceLevelRONA]         INT      NULL,
    [AgentErrorCount]          INT      NULL,
    [VRUTime]                  INT      NULL,
    [CTVRUTime]                INT      NULL,
    [CallsOnHold]              INT      NULL,
    [MaxHoldTime]              INT      NULL,
    [ReportingHalfHour]        INT      NULL,
    [ReportingInterval]        INT      NULL,
    [MaxCallWaitTime]          INT      NULL,
    [MaxCallsQueued]           INT      NULL,
    [RunID]                    INT      NULL,
    [EffectiveFrom]            DATETIME NULL,
    [CheckSum]                 INT      NULL,
    [EffectiveTo]              DATETIME CONSTRAINT [dfCallTypeIntervalEffectiveTo] DEFAULT ('2999-12-31') NULL,
    CONSTRAINT [PKCallTypeIntervalID] PRIMARY KEY NONCLUSTERED ([CallTypeIntervalID] ASC)
);


GO
CREATE CLUSTERED INDEX [CX_CallTypeInterval]
    ON [Cisco].[CallTypeInterval]([Date] ASC, [Time] ASC, [CallTypeKey] ASC);

