CREATE TABLE [Cisco].[SkillGroupInterval] (
    [SkillGroupIntervalID]    BIGINT   IDENTITY (1, 1) NOT NULL,
    [Date]                    DATE     NULL,
    [Time]                    TIME (7) NULL,
    [PrecisionQueueKey]       BIGINT   NULL,
    [SkillGroupKey]           BIGINT   NULL,
    [SourceSystemKey]         INT      NULL,
    [TimeZone]                INT      NULL,
    [CallbackMessages]        INT      NULL,
    [CallbackMessagesTime]    INT      NULL,
    [AvgHandledCallsTalkTime] INT      NULL,
    [HoldTime]                INT      NULL,
    [HandledCallsTalkTime]    INT      NULL,
    [InternalCalls]           INT      NULL,
    [InternalCallsTime]       INT      NULL,
    [CallsHandled]            INT      NULL,
    [AvgHandledCallsTime]     INT      NULL,
    [HandledCallsTime]        INT      NULL,
    [PercentUtilization]      REAL     NULL,
    [AgentOutCallsTime]       INT      NULL,
    [TalkInTime]              INT      NULL,
    [LoggedOnTime]            INT      NULL,
    [AgentOutCalls]           INT      NULL,
    [TalkOutTime]             INT      NULL,
    [TalkOtherTime]           INT      NULL,
    [AvailTime]               INT      NULL,
    [NotReadyTime]            INT      NULL,
    [TransferInCalls]         INT      NULL,
    [TalkTime]                INT      NULL,
    [TransferInCallsTime]     INT      NULL,
    [WorkReadyTime]           INT      NULL,
    [TransferOutCalls]        INT      NULL,
    [WorkNotReadyTime]        INT      NULL,
    [BusyOtherTime]           INT      NULL,
    [CallsAnswered]           INT      NULL,
    [ReservedStateTime]       INT      NULL,
    [AnswerWaitTime]          INT      NULL,
    [AbandonRingCalls]        INT      NULL,
    [AbandonRingTime]         INT      NULL,
    [AbandonHoldCalls]        INT      NULL,
    [AgentOutCallsTalkTime]   INT      NULL,
    [AgentOutCallsOnHold]     INT      NULL,
    [AgentOutCallsOnHoldTime] INT      NULL,
    [ConsultativeCalls]       INT      NULL,
    [ConsultativeCallsTime]   INT      NULL,
    [ConferencedInCalls]      INT      NULL,
    [ConferencedInCallsTime]  INT      NULL,
    [ConferencedOutCalls]     INT      NULL,
    [ConferencedOutCallsTime] INT      NULL,
    [IncomingCallsOnHoldTime] INT      NULL,
    [IncomingCallsOnHold]     INT      NULL,
    [InternalCallsOnHoldTime] INT      NULL,
    [InternalCallsOnHold]     INT      NULL,
    [InternalCallsRcvdTime]   INT      NULL,
    [InternalCallsRcvd]       INT      NULL,
    [RedirectNoAnsCalls]      INT      NULL,
    [RedirectNoAnsCallsTime]  INT      NULL,
    [ShortCalls]              INT      NULL,
    [BargeInCalls]            INT      NULL,
    [MonitorCalls]            INT      NULL,
    [CallsOffered]            INT      NULL,
    [InterruptedTime]         INT      NULL,
    [AbandonHoldCallsOut]     INT      NULL,
    [RouterCallsOffered]      INT      NULL,
    [RouterCallsAbandToAgent] INT      NULL,
    [ServiceLevel]            REAL     NULL,
    [ReportingHalfHour]       INT      NULL,
    [ReportingInterval]       INT      NULL,
    [RouterMaxCallWaitTime]   INT      NULL,
    [RunID]                   INT      NULL,
    [EffectiveFrom]           DATETIME NULL,
    [EffectiveTo]             DATETIME CONSTRAINT [dfEffectiveTo] DEFAULT ('2999-12-31') NULL,
    [CheckSum]                INT      NULL,
    CONSTRAINT [PKSkillGroupIntervalID] PRIMARY KEY NONCLUSTERED ([SkillGroupIntervalID] ASC)
);


GO
CREATE CLUSTERED INDEX [CX_SkillGroupInterval]
    ON [Cisco].[SkillGroupInterval]([Date] ASC, [Time] ASC, [PrecisionQueueKey] ASC, [SkillGroupKey] ASC);

