CREATE TABLE [Cisco].[TerminationCallDetail] (
    [TerminationCallDetailID]       BIGINT       IDENTITY (1, 1) NOT NULL,
    [MRDomainKey]                   BIGINT       NULL,
    [SourceSystemKey]               INT          NULL,
    [AgentsKey]                     INT          NULL,
    [SkillGroupKey]                 BIGINT       NULL,
    [CallTypeKey]                   INT          NULL,
    [WrapUpDataKey]                 INT          NULL,
    [CallTypeQueueKey]              INT          NULL,
    [PrecisionQueueKey]             INT          NULL,
    [RouterCallKey]                 INT          NULL,
    [Date]                          DATE         NULL,
    [Time]                          TIME (7)     NULL,
    [CallTypeDate]                  DATE         NULL,
    [CallTypeTime]                  TIME (7)     NULL,
    [StartDateUTC]                  DATE         NULL,
    [StartTimeUTC]                  TIME (7)     NULL,
    [TimeZone]                      INT          NULL,
    [PeripheralID]                  SMALLINT     NULL,
    [ANI]                           VARCHAR (52) NULL,
    [RouterCallKeyDay]              INT          NULL,
    [PeripheralCallType]            SMALLINT     NULL,
    [DigitsDialed]                  VARCHAR (40) NULL,
    [PeripheralCallKey]             INT          NULL,
    [NetworkTime]                   INT          NULL,
    [Duration]                      INT          NULL,
    [RingTime]                      INT          NULL,
    [DelayTime]                     INT          NULL,
    [TimeToAband]                   INT          NULL,
    [HoldTime]                      INT          NULL,
    [TalkTime]                      INT          NULL,
    [WorkTime]                      INT          NULL,
    [LocalQTime]                    INT          NULL,
    [ConferenceTime]                INT          NULL,
    [Variable1]                     VARCHAR (40) NULL,
    [Variable2]                     VARCHAR (40) NULL,
    [Variable3]                     VARCHAR (40) NULL,
    [Variable4]                     VARCHAR (40) NULL,
    [NewTransaction]                CHAR (1)     NULL,
    [TrunkGroupID]                  INT          NULL,
    [DNIS]                          VARCHAR (32) NULL,
    [InstrumentPortNumber]          INT          NULL,
    [AgentPeripheralNumber]         VARCHAR (32) NULL,
    [ICRCallKey]                    INT          NULL,
    [ICRCallKeyParent]              INT          NULL,
    [ICRCallKeyChild]               INT          NULL,
    [AnsweredWithinServiceLevel]    CHAR (1)     NULL,
    [Priority]                      SMALLINT     NULL,
    [Trunk]                         INT          NULL,
    [SourceAgentPeripheralNumber]   VARCHAR (32) NULL,
    [SourceAgentSkillTargetID]      INT          NULL,
    [CallDispositionFlag]           INT          NULL,
    [RouterCallKeySequenceNumber]   INT          NULL,
    [CED]                           VARCHAR (30) NULL,
    [BadCallTag]                    CHAR (1)     NULL,
    [ApplicationTaskDisposition]    INT          NULL,
    [NetQTime]                      INT          NULL,
    [RoutedSkillGroupSkillTargetID] INT          NULL,
    [RoutedServiceSkillTargetID]    INT          NULL,
    [RoutedAgentSkillTargetID]      INT          NULL,
    [Originated]                    CHAR (1)     NULL,
    [CallReferenceID]               VARCHAR (32) NULL,
    [PstnTrunkGroupID]              VARCHAR (32) NULL,
    [PstnTrunkGroupChannelNumber]   INT          NULL,
    [NetworkSkillGroupQTime]        INT          NULL,
    [ProtocolID]                    INT          NULL,
    [PrecisionQueueStepOrder]       INT          NULL,
    [RunID]                         INT          NULL,
    [EffectiveFrom]                 DATETIME     NULL,
    [CheckSum]                      INT          NULL,
    [EffectiveTo]                   DATETIME     CONSTRAINT [dfTerminationCallDetailEffectiveTo] DEFAULT ('2999-12-31') NULL,
    CONSTRAINT [PKTerminationCallDetailID] PRIMARY KEY NONCLUSTERED ([TerminationCallDetailID] ASC)
);


GO
CREATE CLUSTERED INDEX [CX_TerminationCallDetail]
    ON [Cisco].[TerminationCallDetail]([RouterCallKey] ASC, [PeripheralCallKey] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_TerminationCallDetail_Column_Keys]
    ON [Cisco].[TerminationCallDetail]([AgentsKey] ASC, [SkillGroupKey] ASC, [CallTypeKey] ASC, [CallTypeQueueKey] ASC);

